lib/fintech_web/router.ex
defmodule FintechWeb.Router do
  use FintechWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plug.Telemetry, event_prefix: [:fintech, :plug]
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FintechWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/banks", BankController
    resources "/customers", CustomerController
    resources "/accounts", AccountController
    resources "/transferences", TransferenceController

  end

  # Other scopes may use custom stacks.
  # scope "/api", FintechWeb do
  #   pipe_through :api
  # end
end

lib/fintech_web/templates/page/index.html.eex
<br/>
<section class="phx-hero">
  <h1>Pagantis Technical test</h1>
  <p>Project regarding technical test for Pagantis<br/>This is a project to meet requirements for pagantis techinical test.</p>
  <br/>
  <p>Required entities for the project:</p>
  <ul>
    <li>
      <%= link "Banks", to: Routes.bank_path(@conn, :index) %>
    </li>
    <li>
      <%= link "Customers", to: Routes.customer_path(@conn, :index) %>
    </li>
    <li>
      <%= link "Accounts", to: Routes.account_path(@conn, :index) %>
    </li>
    <li>
      <%= link "Transferences", to: Routes.transference_path(@conn, :index) %>
    </li>
  </ul>
</section>

<section class="row">
  <article class="column">
    <h2>Personal interests</h2>
    <ul>
      <li>
        <a href="https://elixir-lang.org/">Elixir</a>
      </li>
      <li>
        <a href="https://www.rust-lang.org/">Rust</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>About me</h2>
    <ul>
      <li>
        <a href="https://github.com/kamigari">Github</a>
      </li>
    </ul>
  </article>
</section>